version: '3.8'

services:
  postgres-main:
    image: postgis/postgis:18-3.6-alpine
    container_name: buyer-backend-postgres-main
    environment:
      POSTGRES_DB: agentbackend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - .volumes/postgres-main-data:/var/lib/postgresql/data 700
      - ./migrations/001_complete_schema.sql:/docker-entrypoint-initdb.d/001_complete_schema.sql:ro
      - ./seeds/001_complete_seed_data.sql:/docker-entrypoint-initdb.d/001_complete_seed_data.sql:ro
    networks:
      - buyer-backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agentbackend"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  minio:
    image: minio/minio:latest
    container_name: buyer-backend-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: mypassword
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - .volumes/minio-data:/data
    networks:
      - buyer-backend-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
  # # Buyer Backend C++ Application (Enable it by uncommenting)
  # buyer-backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: buyer-backend-app
  #   environment:
  #     DATABASE_URL: postgres://postgres:mypassword@postgres-main:5432/agentbackend
  #     MINIO_ENDPOINT: minio:9000
  #     MINIO_ACCESS_KEY: minioadmin
  #     MINIO_SECRET_KEY: mypassword
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - postgres-main
  #     - minio
  #   networks:
  #     - buyer-backend-network
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:5555/"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  #   restart: unless-stopped
networks:
  buyer-backend-network:
    driver: bridge

volumes:
  postgres-main-data:
  minio-data:
